#!/bin/sh
set -e

configure() {
	# Divert Calls daemon config
	if ! [ -e "/usr/lib/calls-config-ofono/sm.puri.Calls.desktop.mm" ]; then
		dpkg-divert --rename --package hybris-mobian-quirks-calls-config-ofono --divert "/usr/lib/calls-config-ofono/sm.puri.Calls.desktop.mm" --add "/etc/xdg/autostart/sm.puri.Calls.desktop"
		ln -s "/usr/lib/calls-config-ofono/sm.puri.Calls.desktop.ofono" "/etc/xdg/autostart/sm.puri.Calls.desktop"
	fi

}

case "$1" in
	"configure")
		configure
		;;
esac
