#!/bin/bash
#
# Sets the hostname by looking at an eventual clue in the adaptation and,
# failing that, by looking at the Android vendor.

set -e

PREFERRED_HOSTNAME_FILE="/var/lib/droidian/preferred_hostname"
ANDROID_VENDOR_PROPS="/vendor/build.prop"

if [ -e "${PREFERRED_HOSTNAME_FILE}" ]; then
	new_hostname="$(cat ${PREFERRED_HOSTNAME_FILE})"
elif [ -e "${ANDROID_VENDOR_PROPS}" ]; then
	new_hostname="$(grep ro.product.vendor.model= ${ANDROID_VENDOR_PROPS} | cut -d'=' -f2)"
fi

[ -n "${new_hostname}" ] || exit 1

# TODO: since runonce/runonce@hostname came late in the bookworm cycle,
# rename only installations still called 'droidian'...
# This can be removed in future once we move away on bookworm
[ "$(hostnamectl hostname)" == "droidian" ] || exit 0

hostnamectl hostname ${new_hostname}
